move nbgv-python install into release group (#291)
moved `nbgv-python` into a separate "release" dependency-group, so that
`uv sync` doesnt throw an error when developer doesnt have it installed

error that I was getting:
```
TypeError: NbgvCommandError.__init__() missing 3 required positional arguments: 'returncode', 'stdout', and 'stderr'
      hint: This usually indicates a problem with the package or the build environment.
```
no impact on existing release pipeline/samples:
<img width="816" height="349" alt="image"
src="https://github.com/user-attachments/assets/4c21cfc1-143f-470f-a55c-64718459f82a"
/>




to re-install:
run `uv sync --group release`

Co-authored-by: lilydu <lilydu+odspmdb@microsoft.com>